### ISSUE TITLE
Definição da Tecnologia

### ISSUE THREAD

**Issue by FerdRosa** [es20231/eqp1#1]
## **Tecnologias:** 

Linguagem Python com uso de microframework Flask e integração a um banco de dados MySQL.

### **Discussão:** 

Decisão acerca das tecnologias fundamentadas na aptidão do grupo com a linguagem de programação Python e devido à simplicidade e flexibilidade de desenvolvimento de projetos garantidas pelo microframework Flask. A decisão pelo uso do MySQL está relacionada com a simplicidade de uso e conexão e do menor consumo de memória adotado por esse banco de dados.

**Comment by armandossrecife** [comment]
@armandossrecife ok!
