### ISSUE TITLE
Documento de especificação de requisitos - Diagrama de casos de uso

### ISSUE THREAD

**Issue by FerdRosa** [es20231/eqp1#11]
# Diagrama de Caso de Uso

## Divisão e inicio de do diagrama, que será realizado no PlantText Uml

O Diagrama pode ser acessado no [Diagrama de caso de uso](https://www.planttext.com/api/plantuml/svg/hLTBRjim4Dth5DorNVW2NXGnOhS8aBQ6WtJFI6E7g4GQ_015RrDqqGCKFO4lrg6e7qNgPzVmGYRVUpDyCnh9TqfJgKsH9udwnZYHGa6IQAPp85j6Jv8Mb6H0xgaIobuyAq5Mv1DBfR2RIVA6RE78EBlyllmI94CKrKA2IjQRhC1rfINDX5oJPFsipEMdP68TOwLr1AD4i4yL-N86IV7dNvIkXSXgzPwyVHGdnjybNZXlnuTlZ0QkMKfBxVxk0L9JHRA1WJm1VwKXwcGZbO1xmJK2gc1kVqlLwukWCYCrRn3WfOse2DLHCCwHdOoaakn17bdkoj783n8nhZ1w3F6LAKDpzWEb2p1Jydx6GNARSzwQEv5rLP5SWmLy4Bfqr04NadUhWbe09MbLa2NipwA0XPIgCMPnTj_Jt33PzND9g2seLBBQqjcLgDMK7wvTTeoz5EaI_2EpGuDeOMzR_7Pf4IsFr2mJF76PjsKDApho4-IGCi6fv-28v1WjjXhS1hFmkupP11ght7HgEnZdsaoXi3t6Y_mH9F2KESzmEEBteQ0du8gSpOkz_t0LLURX-cNzJu9DBvI80dtXMi94W2j8Nlhuv36vHgi8vec3G9QNnKJKmSdOdhVcePp26Nc0ir1CN_wuSit3ESq7ha2oveHSt20MkdoJt60JPBvghxEdSl2q3x4AyL7zQx8AHe3BhLLRdCUmOhWM39H9R3q39e47g2JtheFhnq8OR1m_sFF138_DzQ6ntdgfOYEwknru59sQu_kXHkUG8qf3gEePQgHcOmPFyV5jWklH4itBm0cv5qzyi-d9pPZOGS_69QwPcbFIGpj-koyYLTbsN573jeoY_2J6RPxpsemNgiF3rm2_t97zm3_Z_cf5fMR1_4E1Ki5H5iXqaayz9sEw2y1-acdNUS2wrHrsjN9rvvWYedrhriqexQbpQdtioTlF7V0C_rp_0m00).

**Comment by armandossrecife** [comment]
Onde estão os artefatos gerados?
